openapi: 3.2.0
info:
  title: Fermyon Cloud Channels API
  version: '1.0'
security:
- Bearer: []
tags:
- name: Channels
paths:
  /api/channels:
    get:
      tags:
      - Channels
      parameters:
      - name: searchText
        in: query
        schema:
          type: string
          default: ''
      - name: pageIndex
        in: query
        schema:
          type: integer
          format: int32
          default: 0
      - name: pageSize
        in: query
        schema:
          type: integer
          format: int32
          default: 50
      - name: sortBy
        in: query
        schema:
          type: string
          default: Name
      - name: IsSortedAscending
        in: query
        schema:
          type: boolean
          default: true
      - name: Api-Version
        in: header
        description: The requested API version
        schema:
          type: string
          default: '1.0'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ChannelItemPage'
            application/json:
              schema:
                $ref: '#/components/schemas/ChannelItemPage'
            text/json:
              schema:
                $ref: '#/components/schemas/ChannelItemPage'
      summary: Get api channels
      x-summary-source: derived
      operationId: getApiChannels
      x-operation-id-source: derived
    post:
      tags:
      - Channels
      parameters:
      - name: Api-Version
        in: header
        description: The requested API version
        schema:
          type: string
          default: '1.0'
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/CreateChannelCommand'
          application/json:
            schema:
              $ref: '#/components/schemas/CreateChannelCommand'
          text/json:
            schema:
              $ref: '#/components/schemas/CreateChannelCommand'
          application/*+json:
            schema:
              $ref: '#/components/schemas/CreateChannelCommand'
        required: true
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: string
                format: uuid
            application/json:
              schema:
                type: string
                format: uuid
            text/json:
              schema:
                type: string
                format: uuid
      summary: Create api channels
      x-summary-source: derived
      operationId: postApiChannels
      x-operation-id-source: derived
  /api/channels/{id}:
    get:
      tags:
      - Channels
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: Api-Version
        in: header
        description: The requested API version
        schema:
          type: string
          default: '1.0'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ChannelItem'
            application/json:
              schema:
                $ref: '#/components/schemas/ChannelItem'
            text/json:
              schema:
                $ref: '#/components/schemas/ChannelItem'
      summary: Get api channels by id
      x-summary-source: derived
      operationId: getApiChannelsById
      x-operation-id-source: derived
    put:
      tags:
      - Channels
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: Api-Version
        in: header
        description: The requested API version
        schema:
          type: string
          default: '1.0'
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/UpdateChannelCommand'
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateChannelCommand'
          text/json:
            schema:
              $ref: '#/components/schemas/UpdateChannelCommand'
          application/*+json:
            schema:
              $ref: '#/components/schemas/UpdateChannelCommand'
        required: true
      responses:
        '200':
          description: Success
      summary: Replace api channels by id
      x-summary-source: derived
      operationId: putApiChannelsById
      x-operation-id-source: derived
    patch:
      tags:
      - Channels
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: Api-Version
        in: header
        description: The requested API version
        schema:
          type: string
          default: '1.0'
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/PatchChannelCommand'
          application/json:
            schema:
              $ref: '#/components/schemas/PatchChannelCommand'
          text/json:
            schema:
              $ref: '#/components/schemas/PatchChannelCommand'
          application/*+json:
            schema:
              $ref: '#/components/schemas/PatchChannelCommand'
        required: true
      responses:
        '200':
          description: Success
      summary: Update api channels by id
      x-summary-source: derived
      operationId: patchApiChannelsById
      x-operation-id-source: derived
    delete:
      tags:
      - Channels
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: Api-Version
        in: header
        description: The requested API version
        schema:
          type: string
          default: '1.0'
      responses:
        '200':
          description: Success
      summary: Delete api channels by id
      x-summary-source: derived
      operationId: deleteApiChannelsById
      x-operation-id-source: derived
  /api/channels/{channelId}/desired-status:
    put:
      tags:
      - Channels
      parameters:
      - name: channelId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: Api-Version
        in: header
        description: The requested API version
        schema:
          type: string
          default: '1.0'
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/UpdateDesiredStatusCommand'
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateDesiredStatusCommand'
          text/json:
            schema:
              $ref: '#/components/schemas/UpdateDesiredStatusCommand'
          application/*+json:
            schema:
              $ref: '#/components/schemas/UpdateDesiredStatusCommand'
        required: true
      responses:
        '200':
          description: Success
      summary: Replace api channels by channel id desired status
      x-summary-source: derived
      operationId: putApiChannelsByChannelIdDesiredStatus
      x-operation-id-source: derived
  /api/channels/{id}/logs:
    get:
      tags:
      - Channels
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: max
        in: query
        schema:
          type: integer
          format: int32
      - name: since
        in: query
        schema:
          type: string
      - name: Api-Version
        in: header
        description: The requested API version
        schema:
          type: string
          default: '1.0'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/GetChannelLogsVm'
            application/json:
              schema:
                $ref: '#/components/schemas/GetChannelLogsVm'
            text/json:
              schema:
                $ref: '#/components/schemas/GetChannelLogsVm'
      summary: Get api channels by id logs
      x-summary-source: derived
      operationId: getApiChannelsByIdLogs
      x-operation-id-source: derived
  /api/channels/{id}/logs/raw:
    get:
      tags:
      - Channels
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: max
        in: query
        schema:
          type: integer
          format: int32
      - name: since
        in: query
        schema:
          type: string
      - name: Api-Version
        in: header
        description: The requested API version
        schema:
          type: string
          default: '1.0'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/GetChannelRawLogsVm'
            application/json:
              schema:
                $ref: '#/components/schemas/GetChannelRawLogsVm'
            text/json:
              schema:
                $ref: '#/components/schemas/GetChannelRawLogsVm'
      summary: Get api channels by id logs raw
      x-summary-source: derived
      operationId: getApiChannelsByIdLogsRaw
      x-operation-id-source: derived
  /api/channels/{id}/healthz:
    get:
      tags:
      - Channels
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: Api-Version
        in: header
        description: The requested API version
        schema:
          type: string
          default: '1.0'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/HealthCheckResult'
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheckResult'
            text/json:
              schema:
                $ref: '#/components/schemas/HealthCheckResult'
      summary: Get api channels by id healthz
      x-summary-source: derived
      operationId: getApiChannelsByIdHealthz
      x-operation-id-source: derived
components:
  schemas:
    Entry:
      type: object
      properties:
        meta:
          $ref: '#/components/schemas/Meta'
        logLines:
          type: array
          items:
            $ref: '#/components/schemas/LogLine'
      additionalProperties: false
    AppSummaryDto:
      required:
      - channels
      - id
      - name
      - storageId
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          minLength: 1
          type: string
        storageId:
          minLength: 1
          type: string
        channels:
          type: array
          items:
            $ref: '#/components/schemas/AppChannelListItem'
        lastModified:
          type: string
          format: date-time
      additionalProperties: false
    CreateChannelCommand:
      required:
      - appId
      - name
      - revisionSelectionStrategy
      type: object
      properties:
        appId:
          type: string
          format: uuid
        name:
          minLength: 1
          type: string
        revisionSelectionStrategy:
          $ref: '#/components/schemas/ChannelRevisionSelectionStrategy'
        rangeRule:
          type:
          - string
          - 'null'
        activeRevisionId:
          type:
          - string
          - 'null'
          format: uuid
      additionalProperties: false
    GuidNullableField:
      type: string
      properties:
        value:
          type:
          - string
          - 'null'
          format: uuid
      additionalProperties: false
    UpdateDesiredStatusCommand:
      required:
      - channelId
      - desiredStatus
      type: object
      properties:
        channelId:
          type: string
          format: uuid
        desiredStatus:
          $ref: '#/components/schemas/DesiredStatus'
      additionalProperties: false
    HealthCheckResult:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/ApiHealthStatus'
      additionalProperties: false
    ChannelRevisionSelectionStrategyField:
      type: string
      properties:
        value:
          $ref: '#/components/schemas/ChannelRevisionSelectionStrategy'
      additionalProperties: false
    ApiHealthStatus:
      enum:
      - Healthy
      - Unhealthy
      - Degraded
      type: string
    ChannelItemPage:
      required:
      - isLastPage
      - items
      - pageIndex
      - pageSize
      - totalItems
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/ChannelItem'
        totalItems:
          type: integer
          format: int32
        pageIndex:
          type: integer
          format: int32
        pageSize:
          type: integer
          format: int32
        isLastPage:
          type: boolean
          readOnly: true
      additionalProperties: false
    StringField:
      type: string
      properties:
        value:
          type: string
      additionalProperties: false
    ChannelItem:
      required:
      - appId
      - desiredStatus
      - domain
      - environmentVariables
      - id
      - name
      - revisionSelectionStrategy
      type: object
      properties:
        id:
          type: string
          format: uuid
        appId:
          type: string
          format: uuid
        name:
          minLength: 1
          type: string
        domain:
          minLength: 1
          type: string
        revisionSelectionStrategy:
          $ref: '#/components/schemas/ChannelRevisionSelectionStrategy'
        desiredStatus:
          minLength: 1
          type: string
        activeRevision:
          $ref: '#/components/schemas/RevisionItem'
        lastPublishAt:
          type:
          - string
          - 'null'
          format: date-time
        rangeRule:
          type:
          - string
          - 'null'
        lastModified:
          type: string
          format: date-time
        appSummary:
          $ref: '#/components/schemas/AppSummaryDto'
        environmentVariables:
          type: array
          items:
            $ref: '#/components/schemas/EnvironmentVariableItem'
      additionalProperties: false
    RevisionItem:
      required:
      - appId
      - components
      - id
      - revisionNumber
      type: object
      properties:
        id:
          type: string
          format: uuid
        appId:
          type: string
          format: uuid
        revisionNumber:
          minLength: 1
          type: string
        components:
          type: array
          items:
            $ref: '#/components/schemas/RevisionComponentDto'
          readOnly: true
        lastModified:
          type: string
          format: date-time
      additionalProperties: false
    LogLine:
      type: object
      properties:
        time:
          type: string
        source:
          type: string
        line:
          type: string
      additionalProperties: false
    Meta:
      type: object
      properties:
        appId:
          type: string
        channelId:
          type: string
        deploymentId:
          type: string
        requestId:
          type: string
        triggerId:
          type: string
        componentId:
          type: string
      additionalProperties: false
    GetChannelRawLogsVm:
      required:
      - entries
      type: object
      properties:
        entries:
          type: array
          items:
            $ref: '#/components/schemas/Entry'
      additionalProperties: false
    DesiredStatus:
      enum:
      - Running
      - Dead
      type: string
    RevisionComponentDto:
      required:
      - id
      - name
      - source
      type: object
      properties:
        id:
          type: string
          format: uuid
        source:
          minLength: 1
          type: string
        name:
          minLength: 1
          type: string
        route:
          type:
          - string
          - 'null'
        type:
          type:
          - string
          - 'null'
      additionalProperties: false
    PatchChannelCommand:
      type: object
      properties:
        channelId:
          type: string
          format: uuid
        name:
          $ref: '#/components/schemas/StringField'
        domain:
          $ref: '#/components/schemas/StringField'
        revisionSelectionStrategy:
          $ref: '#/components/schemas/ChannelRevisionSelectionStrategyField'
        rangeRule:
          $ref: '#/components/schemas/StringField'
        activeRevisionId:
          $ref: '#/components/schemas/GuidNullableField'
      additionalProperties: false
    GetChannelLogsVm:
      required:
      - logs
      type: object
      properties:
        logs:
          type: array
          items:
            type: string
      additionalProperties: false
    UpdateChannelCommand:
      required:
      - id
      - name
      - revisionSelectionStrategy
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          minLength: 1
          type: string
        revisionSelectionStrategy:
          $ref: '#/components/schemas/ChannelRevisionSelectionStrategy'
        rangeRule:
          type:
          - string
          - 'null'
        activeRevisionId:
          type:
          - string
          - 'null'
          format: uuid
      additionalProperties: false
    ChannelRevisionSelectionStrategy:
      enum:
      - UseRangeRule
      - UseSpecifiedRevision
      type: string
    AppChannelListItem:
      required:
      - created
      - id
      - name
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          minLength: 1
          type: string
        activeRevisionNumber:
          type: string
        domain:
          type: string
        created:
          type: string
          format: date-time
        healthStatus:
          $ref: '#/components/schemas/ApiHealthStatus'
        lastModified:
          type: string
          format: date-time
      additionalProperties: false
    EnvironmentVariableItem:
      required:
      - channelId
      - key
      - value
      type: object
      properties:
        channelId:
          type: string
          format: uuid
        key:
          minLength: 1
          type: string
        value:
          minLength: 1
          type: string
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: apiKey
      description: 'JWT Authorization header using the Bearer scheme. Example: "Authorization: Bearer {token}"'
      name: Authorization
      in: header
