openapi: 3.2.0
info:
  title: Fermyon Cloud Custom Domains API
  version: '1.0'
security:
- Bearer: []
tags:
- name: Custom Domains
paths:
  /api/custom-domains/{domainName}:
    get:
      tags:
      - Custom Domains
      parameters:
      - name: domainName
        in: path
        required: true
        schema:
          type: string
      - name: Api-Version
        in: header
        description: The requested API version
        schema:
          type: string
          default: '1.0'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/DomainItem'
            application/json:
              schema:
                $ref: '#/components/schemas/DomainItem'
            text/json:
              schema:
                $ref: '#/components/schemas/DomainItem'
      summary: Get api custom domains by domain name
      x-summary-source: derived
      operationId: getApiCustomDomainsByDomainName
      x-operation-id-source: derived
components:
  schemas:
    DnsRecord:
      required:
      - name
      - ttl
      - type
      - value
      type: object
      properties:
        type:
          minLength: 1
          type: string
        name:
          minLength: 1
          type: string
        value:
          minLength: 1
          type: string
        ttl:
          type: integer
          format: int32
      additionalProperties: false
    DomainItem:
      required:
      - dnsRecords
      - name
      - validationStatus
      type: object
      properties:
        name:
          minLength: 1
          type: string
        validationStatus:
          minLength: 1
          type: string
        validatedAt:
          type:
          - string
          - 'null'
          format: date-time
        lastModified:
          type: string
          format: date-time
        dnsRecords:
          type: array
          items:
            $ref: '#/components/schemas/DnsRecord'
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: apiKey
      description: 'JWT Authorization header using the Bearer scheme. Example: "Authorization: Bearer {token}"'
      name: Authorization
      in: header
