openapi: 3.2.0
info:
  title: Fermyon Cloud Key Value Stores API
  version: '1.0'
security:
- Bearer: []
tags:
- name: Key Value Stores
paths:
  /api/key-value-stores/{store}:
    post:
      tags:
      - Key Value Stores
      parameters:
      - name: store
        in: path
        required: true
        schema:
          type: string
      - name: Api-Version
        in: header
        description: The requested API version
        schema:
          type: string
          default: '1.0'
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/ResourceLabel'
          application/json:
            schema:
              $ref: '#/components/schemas/ResourceLabel'
          text/json:
            schema:
              $ref: '#/components/schemas/ResourceLabel'
          application/*+json:
            schema:
              $ref: '#/components/schemas/ResourceLabel'
      responses:
        '200':
          description: Success
      summary: Create api key value stores by store
      x-summary-source: derived
      operationId: postApiKeyValueStoresByStore
      x-operation-id-source: derived
    delete:
      tags:
      - Key Value Stores
      parameters:
      - name: store
        in: path
        required: true
        schema:
          type: string
      - name: Api-Version
        in: header
        description: The requested API version
        schema:
          type: string
          default: '1.0'
      responses:
        '200':
          description: Success
      summary: Delete api key value stores by store
      x-summary-source: derived
      operationId: deleteApiKeyValueStoresByStore
      x-operation-id-source: derived
  /api/key-value-stores:
    get:
      tags:
      - Key Value Stores
      parameters:
      - name: appId
        in: query
        schema:
          type: string
          format: uuid
      - name: Api-Version
        in: header
        description: The requested API version
        schema:
          type: string
          default: '1.0'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/KeyValueStoresList'
            application/json:
              schema:
                $ref: '#/components/schemas/KeyValueStoresList'
            text/json:
              schema:
                $ref: '#/components/schemas/KeyValueStoresList'
      summary: Get api key value stores
      x-summary-source: derived
      operationId: getApiKeyValueStores
      x-operation-id-source: derived
  /api/key-value-stores/{store}/links:
    post:
      tags:
      - Key Value Stores
      parameters:
      - name: store
        in: path
        required: true
        schema:
          type: string
      - name: Api-Version
        in: header
        description: The requested API version
        schema:
          type: string
          default: '1.0'
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/ResourceLabel'
          application/json:
            schema:
              $ref: '#/components/schemas/ResourceLabel'
          text/json:
            schema:
              $ref: '#/components/schemas/ResourceLabel'
          application/*+json:
            schema:
              $ref: '#/components/schemas/ResourceLabel'
        required: true
      responses:
        '200':
          description: Success
      summary: Create api key value stores by store links
      x-summary-source: derived
      operationId: postApiKeyValueStoresByStoreLinks
      x-operation-id-source: derived
    delete:
      tags:
      - Key Value Stores
      parameters:
      - name: store
        in: path
        required: true
        schema:
          type: string
      - name: Api-Version
        in: header
        description: The requested API version
        schema:
          type: string
          default: '1.0'
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/ResourceLabel'
          application/json:
            schema:
              $ref: '#/components/schemas/ResourceLabel'
          text/json:
            schema:
              $ref: '#/components/schemas/ResourceLabel'
          application/*+json:
            schema:
              $ref: '#/components/schemas/ResourceLabel'
        required: true
      responses:
        '200':
          description: Success
      summary: Delete api key value stores by store links
      x-summary-source: derived
      operationId: deleteApiKeyValueStoresByStoreLinks
      x-operation-id-source: derived
  /api/key-value-stores/{store}/rename:
    patch:
      tags:
      - Key Value Stores
      parameters:
      - name: store
        in: path
        required: true
        schema:
          type: string
      - name: Api-Version
        in: header
        description: The requested API version
        schema:
          type: string
          default: '1.0'
      requestBody:
        content:
          application/json-patch+json:
            schema:
              type: string
          application/json:
            schema:
              type: string
          text/json:
            schema:
              type: string
          application/*+json:
            schema:
              type: string
        required: true
      responses:
        '200':
          description: Success
      summary: Update api key value stores by store rename
      x-summary-source: derived
      operationId: patchApiKeyValueStoresByStoreRename
      x-operation-id-source: derived
components:
  schemas:
    KeyValueStoreItem:
      required:
      - links
      - name
      type: object
      properties:
        name:
          minLength: 1
          type: string
        links:
          type: array
          items:
            $ref: '#/components/schemas/ResourceLabel'
      additionalProperties: false
    KeyValueStoresList:
      required:
      - keyValueStores
      type: object
      properties:
        keyValueStores:
          type: array
          items:
            $ref: '#/components/schemas/KeyValueStoreItem'
      additionalProperties: false
    ResourceLabel:
      required:
      - appId
      - label
      type: object
      properties:
        label:
          minLength: 1
          type: string
        appId:
          type: string
          format: uuid
        appName:
          type: string
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: apiKey
      description: 'JWT Authorization header using the Bearer scheme. Example: "Authorization: Bearer {token}"'
      name: Authorization
      in: header
