openapi: 3.2.0
info:
  title: Fermyon Cloud Device Codes API
  version: '1.0'
security:
- Bearer: []
tags:
- name: device-codes
paths:
  /api/device-codes:
    post:
      tags:
      - device-codes
      parameters:
      - name: Api-Version
        in: header
        description: The requested API version
        schema:
          type: string
          default: '1.0'
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/CreateDeviceCodeCommand'
          application/json:
            schema:
              $ref: '#/components/schemas/CreateDeviceCodeCommand'
          text/json:
            schema:
              $ref: '#/components/schemas/CreateDeviceCodeCommand'
          application/*+json:
            schema:
              $ref: '#/components/schemas/CreateDeviceCodeCommand'
        required: true
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/DeviceCodeItem'
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceCodeItem'
            text/json:
              schema:
                $ref: '#/components/schemas/DeviceCodeItem'
      summary: Create api device codes
      x-summary-source: derived
      operationId: postApiDeviceCodes
      x-operation-id-source: derived
  /api/device-codes/{userCode}:
    get:
      tags:
      - device-codes
      parameters:
      - name: userCode
        in: path
        required: true
        schema:
          type: string
      - name: Api-Version
        in: header
        description: The requested API version
        schema:
          type: string
          default: '1.0'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/DeviceCodeDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceCodeDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/DeviceCodeDetails'
      summary: Get api device codes by user code
      x-summary-source: derived
      operationId: getApiDeviceCodesByUserCode
      x-operation-id-source: derived
  /api/device-codes/activate:
    post:
      tags:
      - device-codes
      parameters:
      - name: Api-Version
        in: header
        description: The requested API version
        schema:
          type: string
          default: '1.0'
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/ActivateDeviceCodeCommand'
          application/json:
            schema:
              $ref: '#/components/schemas/ActivateDeviceCodeCommand'
          text/json:
            schema:
              $ref: '#/components/schemas/ActivateDeviceCodeCommand'
          application/*+json:
            schema:
              $ref: '#/components/schemas/ActivateDeviceCodeCommand'
        required: true
      responses:
        '200':
          description: Success
      summary: Create api device codes activate
      x-summary-source: derived
      operationId: postApiDeviceCodesActivate
      x-operation-id-source: derived
components:
  schemas:
    CreateDeviceCodeCommand:
      required:
      - clientId
      type: object
      properties:
        clientId:
          type: string
          format: uuid
      additionalProperties: false
    DeviceCodeItem:
      required:
      - deviceCode
      - expiresIn
      - interval
      - userCode
      - verificationUrl
      type: object
      properties:
        deviceCode:
          minLength: 1
          type: string
        userCode:
          minLength: 1
          type: string
        verificationUrl:
          minLength: 1
          type: string
        expiresIn:
          type: integer
          format: int64
        interval:
          type: integer
          format: int32
      additionalProperties: false
    ActivateDeviceCodeCommand:
      required:
      - userCode
      type: object
      properties:
        userCode:
          minLength: 1
          type: string
      additionalProperties: false
    DeviceCodeDetails:
      type: object
      properties:
        clientName:
          type: string
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: apiKey
      description: 'JWT Authorization header using the Bearer scheme. Example: "Authorization: Bearer {token}"'
      name: Authorization
      in: header
