openapi: 3.2.0
info:
  title: Fermyon Cloud Payments API
  version: '1.0'
security:
- Bearer: []
tags:
- name: Payments
paths:
  /api/payments/setup-checkout:
    post:
      tags:
      - Payments
      parameters:
      - name: Api-Version
        in: header
        description: The requested API version
        schema:
          type: string
          default: '1.0'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/PaymentIntegrationUrl'
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentIntegrationUrl'
            text/json:
              schema:
                $ref: '#/components/schemas/PaymentIntegrationUrl'
      summary: Create api payments setup checkout
      x-summary-source: derived
      operationId: postApiPaymentsSetupCheckout
      x-operation-id-source: derived
  /api/payments/customer-portal:
    get:
      tags:
      - Payments
      parameters:
      - name: Api-Version
        in: header
        description: The requested API version
        schema:
          type: string
          default: '1.0'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/PaymentIntegrationUrl'
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentIntegrationUrl'
            text/json:
              schema:
                $ref: '#/components/schemas/PaymentIntegrationUrl'
      summary: Get api payments customer portal
      x-summary-source: derived
      operationId: getApiPaymentsCustomerPortal
      x-operation-id-source: derived
  /api/payments/plans:
    get:
      tags:
      - Payments
      parameters:
      - name: Api-Version
        in: header
        description: The requested API version
        schema:
          type: string
          default: '1.0'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PlanItem'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PlanItem'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PlanItem'
      summary: Get api payments plans
      x-summary-source: derived
      operationId: getApiPaymentsPlans
      x-operation-id-source: derived
components:
  schemas:
    PlanItem:
      required:
      - accountPlanType
      - price
      type: object
      properties:
        accountPlanType:
          minLength: 1
          type: string
        price:
          type: number
          format: double
      additionalProperties: false
    PaymentIntegrationUrl:
      type: object
      properties:
        url:
          type: string
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: apiKey
      description: 'JWT Authorization header using the Bearer scheme. Example: "Authorization: Bearer {token}"'
      name: Authorization
      in: header
