openapi: 3.2.0
info:
  title: Fermyon Cloud Personal Access Tokens API
  version: '1.0'
security:
- Bearer: []
tags:
- name: Personal Access Tokens
paths:
  /api/personal-access-tokens:
    post:
      tags:
      - Personal Access Tokens
      parameters:
      - name: Api-Version
        in: header
        description: The requested API version
        schema:
          type: string
          default: '1.0'
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/CreatePersonalAccessTokenCommand'
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePersonalAccessTokenCommand'
          text/json:
            schema:
              $ref: '#/components/schemas/CreatePersonalAccessTokenCommand'
          application/*+json:
            schema:
              $ref: '#/components/schemas/CreatePersonalAccessTokenCommand'
        required: true
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/PersonalAccessTokenValue'
            application/json:
              schema:
                $ref: '#/components/schemas/PersonalAccessTokenValue'
            text/json:
              schema:
                $ref: '#/components/schemas/PersonalAccessTokenValue'
      summary: Create api personal access tokens
      x-summary-source: derived
      operationId: postApiPersonalAccessTokens
      x-operation-id-source: derived
    get:
      tags:
      - Personal Access Tokens
      parameters:
      - name: searchText
        in: query
        schema:
          type: string
          default: ''
      - name: pageIndex
        in: query
        schema:
          type: integer
          format: int32
          default: 0
      - name: pageSize
        in: query
        schema:
          type: integer
          format: int32
          default: 50
      - name: sortBy
        in: query
        schema:
          type: string
          default: CreatedAt
      - name: isSortedAscending
        in: query
        schema:
          type: boolean
          default: false
      - name: Api-Version
        in: header
        description: The requested API version
        schema:
          type: string
          default: '1.0'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/PersonalAccessTokenItemPage'
            application/json:
              schema:
                $ref: '#/components/schemas/PersonalAccessTokenItemPage'
            text/json:
              schema:
                $ref: '#/components/schemas/PersonalAccessTokenItemPage'
      summary: Get api personal access tokens
      x-summary-source: derived
      operationId: getApiPersonalAccessTokens
      x-operation-id-source: derived
  /api/personal-access-tokens/{id}:
    delete:
      tags:
      - Personal Access Tokens
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: Api-Version
        in: header
        description: The requested API version
        schema:
          type: string
          default: '1.0'
      responses:
        '200':
          description: Success
      summary: Delete api personal access tokens by id
      x-summary-source: derived
      operationId: deleteApiPersonalAccessTokensById
      x-operation-id-source: derived
components:
  schemas:
    PersonalAccessTokenItem:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        createdAt:
          type: string
          format: date-time
      additionalProperties: false
    PersonalAccessTokenValue:
      type: object
      properties:
        name:
          type: string
        token:
          type: string
        id:
          type: string
          format: uuid
      additionalProperties: false
    PersonalAccessTokenItemPage:
      required:
      - isLastPage
      - items
      - pageIndex
      - pageSize
      - totalItems
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/PersonalAccessTokenItem'
        totalItems:
          type: integer
          format: int32
        pageIndex:
          type: integer
          format: int32
        pageSize:
          type: integer
          format: int32
        isLastPage:
          type: boolean
          readOnly: true
      additionalProperties: false
    CreatePersonalAccessTokenCommand:
      required:
      - name
      type: object
      properties:
        name:
          minLength: 1
          type: string
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: apiKey
      description: 'JWT Authorization header using the Bearer scheme. Example: "Authorization: Bearer {token}"'
      name: Authorization
      in: header
