openapi: 3.2.0
info:
  title: Fermyon Cloud Oci API
  version: '1.0'
security:
- Bearer: []
tags:
- name: Oci
paths:
  /api/oci:
    get:
      tags:
      - Oci
      parameters:
      - name: Api-Version
        in: header
        description: The requested API version
        schema:
          type: string
          default: '1.0'
      responses:
        '200':
          description: Success
      summary: Get api oci
      x-summary-source: derived
      operationId: getApiOci
      x-operation-id-source: derived
  /api/oci/{name}/manifests/{reference}:
    head:
      tags:
      - Oci
      parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string
      - name: reference
        in: path
        required: true
        schema:
          type: string
      - name: Api-Version
        in: header
        description: The requested API version
        schema:
          type: string
          default: '1.0'
      responses:
        '200':
          description: Success
      summary: Check api oci by name manifests by reference
      x-summary-source: derived
      operationId: headApiOciByNameManifestsByReference
      x-operation-id-source: derived
    put:
      tags:
      - Oci
      parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string
      - name: reference
        in: path
        required: true
        schema:
          type: string
      - name: Api-Version
        in: header
        description: The requested API version
        schema:
          type: string
          default: '1.0'
      responses:
        '200':
          description: Success
      summary: Replace api oci by name manifests by reference
      x-summary-source: derived
      operationId: putApiOciByNameManifestsByReference
      x-operation-id-source: derived
  /api/oci/{name}/blobs/uploads:
    post:
      tags:
      - Oci
      parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string
      - name: Api-Version
        in: header
        description: The requested API version
        schema:
          type: string
          default: '1.0'
      responses:
        '200':
          description: Success
      summary: Create api oci by name blobs uploads
      x-summary-source: derived
      operationId: postApiOciByNameBlobsUploads
      x-operation-id-source: derived
  /api/oci/{name}/blobs/uploads/{digest}:
    get:
      tags:
      - Oci
      parameters:
      - name: digest
        in: path
        required: true
        schema:
          type: string
      - name: name
        in: path
        required: true
        schema:
          type: string
      - name: Api-Version
        in: header
        description: The requested API version
        schema:
          type: string
          default: '1.0'
      responses:
        '200':
          description: Success
      summary: Get api oci by name blobs uploads by digest
      x-summary-source: derived
      operationId: getApiOciByNameBlobsUploadsByDigest
      x-operation-id-source: derived
    put:
      tags:
      - Oci
      parameters:
      - name: digest
        in: path
        required: true
        schema:
          type: string
      - name: name
        in: path
        required: true
        schema:
          type: string
      - name: Api-Version
        in: header
        description: The requested API version
        schema:
          type: string
          default: '1.0'
      responses:
        '200':
          description: Success
      summary: Replace api oci by name blobs uploads by digest
      x-summary-source: derived
      operationId: putApiOciByNameBlobsUploadsByDigest
      x-operation-id-source: derived
    patch:
      tags:
      - Oci
      parameters:
      - name: digest
        in: path
        required: true
        schema:
          type: string
      - name: name
        in: path
        required: true
        schema:
          type: string
      - name: Api-Version
        in: header
        description: The requested API version
        schema:
          type: string
          default: '1.0'
      responses:
        '200':
          description: Success
      summary: Update api oci by name blobs uploads by digest
      x-summary-source: derived
      operationId: patchApiOciByNameBlobsUploadsByDigest
      x-operation-id-source: derived
    delete:
      tags:
      - Oci
      parameters:
      - name: digest
        in: path
        required: true
        schema:
          type: string
      - name: name
        in: path
        required: true
        schema:
          type: string
      - name: Api-Version
        in: header
        description: The requested API version
        schema:
          type: string
          default: '1.0'
      responses:
        '200':
          description: Success
      summary: Delete api oci by name blobs uploads by digest
      x-summary-source: derived
      operationId: deleteApiOciByNameBlobsUploadsByDigest
      x-operation-id-source: derived
components:
  securitySchemes:
    Bearer:
      type: apiKey
      description: 'JWT Authorization header using the Bearer scheme. Example: "Authorization: Bearer {token}"'
      name: Authorization
      in: header
