openapi: 3.2.0
info:
  title: Fermyon Cloud Accounts API
  version: '1.0'
security:
- Bearer: []
tags:
- name: Accounts
paths:
  /api/accounts/{id}:
    get:
      tags:
      - Accounts
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: Api-Version
        in: header
        description: The requested API version
        schema:
          type: string
          default: '1.0'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/AccountDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/AccountDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/AccountDetails'
      summary: Get api accounts by id
      x-summary-source: derived
      operationId: getApiAccountsById
      x-operation-id-source: derived
    patch:
      tags:
      - Accounts
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: Api-Version
        in: header
        description: The requested API version
        schema:
          type: string
          default: '1.0'
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/PatchAccountDetailsCommand'
          application/json:
            schema:
              $ref: '#/components/schemas/PatchAccountDetailsCommand'
          text/json:
            schema:
              $ref: '#/components/schemas/PatchAccountDetailsCommand'
          application/*+json:
            schema:
              $ref: '#/components/schemas/PatchAccountDetailsCommand'
        required: true
      responses:
        '200':
          description: Success
      summary: Update api accounts by id
      x-summary-source: derived
      operationId: patchApiAccountsById
      x-operation-id-source: derived
    delete:
      tags:
      - Accounts
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: Api-Version
        in: header
        description: The requested API version
        schema:
          type: string
          default: '1.0'
      responses:
        '200':
          description: Success
      summary: Delete api accounts by id
      x-summary-source: derived
      operationId: deleteApiAccountsById
      x-operation-id-source: derived
components:
  schemas:
    PatchAccountDetailsCommand:
      type: object
      properties:
        isMarketingEmailOn:
          $ref: '#/components/schemas/BooleanField'
      additionalProperties: false
    AccountDetails:
      type: object
      properties:
        plan:
          $ref: '#/components/schemas/AccountPlanRecord'
        isMarketingEmailOn:
          type: boolean
        createdAt:
          type:
          - string
          - 'null'
          format: date-time
      additionalProperties: false
    AccountPlanType:
      enum:
      - Free
      - Growth
      - Enterprise
      type: string
    AccountPlanRecord:
      type: object
      properties:
        accountType:
          $ref: '#/components/schemas/AccountPlanType'
        cancelAt:
          type:
          - string
          - 'null'
          format: date-time
        cycleStartDate:
          type:
          - string
          - 'null'
          format: date-time
        cycleEndDate:
          type:
          - string
          - 'null'
          format: date-time
        lastModified:
          type:
          - string
          - 'null'
          format: date-time
      additionalProperties: false
    BooleanField:
      type: string
      properties:
        value:
          type: boolean
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: apiKey
      description: 'JWT Authorization header using the Bearer scheme. Example: "Authorization: Bearer {token}"'
      name: Authorization
      in: header
